// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWP_4c4_nAHtQyrHXDONere4DL-0NXw8g',
    appId: '1:905549705126:web:6989f6d39b11325f46e967',
    messagingSenderId: '905549705126',
    projectId: 'medicine-stock-managemen-aab34',
    authDomain: 'medicine-stock-managemen-aab34.firebaseapp.com',
    storageBucket: 'medicine-stock-managemen-aab34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmr24JXPOBQRL0syoTOz-Y8Bcw4ftFcI',
    appId: '1:905549705126:android:b2d06984a97dc00b46e967',
    messagingSenderId: '905549705126',
    projectId: 'medicine-stock-managemen-aab34',
    storageBucket: 'medicine-stock-managemen-aab34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9H5k0K8ZK0kcZDd8N702_nCta2vzdAA',
    appId: '1:905549705126:ios:60cbb6604c88591646e967',
    messagingSenderId: '905549705126',
    projectId: 'medicine-stock-managemen-aab34',
    storageBucket: 'medicine-stock-managemen-aab34.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWP_4c4_nAHtQyrHXDONere4DL-0NXw8g',
    appId: '1:905549705126:web:5c578b793e27f86746e967',
    messagingSenderId: '905549705126',
    projectId: 'medicine-stock-managemen-aab34',
    authDomain: 'medicine-stock-managemen-aab34.firebaseapp.com',
    storageBucket: 'medicine-stock-managemen-aab34.firebasestorage.app',
  );
}
